export const METADATA = {
  "datasets": {
    "census": {
      "name": "Census (ACS Demographics)",
      "sourceName": "American Community Survey (ACS) 5-Year Estimates",
      "sourceUrl": "https://data.census.gov/",
      "coverage": "County-level ACS 5-year estimates aggregated to state and congressional district.",
      "description": "Demographics, education, income distribution, and poverty status across U.S. geographies."
    },
    "gov_spending": {
      "name": "Government Spending",
      "sourceName": "Annual Survey of State and Local Government Finances",
      "sourceUrl": "https://govfinance.reason.org/",
      "coverage": "County-level fiscal year 2022 aggregated to state and congressional district.",
      "description": "Government fiscal health, assets, liabilities, revenues, and expenses."
    },
    "contract_static": {
      "name": "Contract Flow",
      "sourceName": "USAspending.gov",
      "sourceUrl": "https://usaspending.gov/",
      "coverage": "County, congressional district, and state level contract obligations and subawards.",
      "description": "Federal contract awards, direct obligations, and subaward flows."
    },
    "finra": {
      "name": "FINRA Financial Literacy",
      "sourceName": "FINRA National Financial Capability Study",
      "sourceUrl": "https://www.usfinancialcapability.org/",
      "coverage": "County, congressional district, and state level (2021).",
      "description": "Financial literacy, constraints, alternative financing, and related indices."
    }
  },
  "variables": {
    "census": {
      "state": "State name (lowercase)",
      "Total_population": "Total population (ACS 5-year estimate)",
      "Male": "Population: male",
      "Female": "Population: female",
      "Under_5_years": "Population age < 5",
      "5_to_9_years": "Population age 5 to 9",
      "10_to_14_years": "Population age 10 to 14",
      "15_to_19_years": "Population age 15 to 19",
      "20_to_24_years": "Population age 20 to 24",
      "25_to_34_years": "Population age 25 to 34",
      "35_to_44_years": "Population age 35 to 44",
      "45_to_54_years": "Population age 45 to 54",
      "55_to_59_years": "Population age 55 to 59",
      "60_to_64_years": "Population age 60 to 64",
      "65_to_74_years": "Population age 65 to 74",
      "75_to_84_years": "Population age 75 to 84",
      "85_years_and_over": "Population age >= 85",
      "Under_18_years": "Population age < 18",
      "16_years_and_over": "Population age >= 16",
      "18_years_and_over": "Population age >= 18",
      "21_years_and_over": "Population age >= 21",
      "62_years_and_over": "Population age >= 62",
      "65_years_and_over": "Population age >= 65",
      "18_years_and_over_Male": "Population age >= 18: male",
      "18_years_and_over_Female": "Population age >= 18: female",
      "65_years_and_over_Male": "Population age >= 65: male",
      "65_years_and_over_Female": "Population age >= 65: female",
      "White": "Population by race: White",
      "Black": "Population by race: Black",
      "American_Indian_Alaska_Native": "Population by race: American Indian Alaska Native",
      "Asian": "Population by race: Asian",
      "Pacific_Islander": "Population by race: Pacific Islander",
      "Other_race": "Population by race: Other race",
      "Population_25_years_and_over": "Population age >= 25",
      "Less_than_9th_grade": "Educational attainment(age >= 25): Less than 9th grade",
      "9th_to_12th_grade_no_diploma": "Educational attainment(age >= 25): 9th to 12th grade no diploma",
      "High_school_graduate": "Educational attainment(age >= 25): High school graduate",
      "Some_college_no_degree": "Educational attainment(age >= 25): Some college no degree",
      "Associate_degree": "Educational attainment(age >= 25): Associate degree",
      "Bachelor_degree": "Educational attainment(age >= 25): Bachelor degree",
      "Graduate_or_professional_degree": "Educational attainment(age >= 25): Graduate or professional degree",
      "High_school_graduate_or_higher": "Educational attainment(age >= 25): High school graduate or higher",
      "Bachelor_degree_or_higher": "Educational attainment(age >= 25): Bachelor degree or higher",
      "Total_households": "Total number of households",
      "Less_than_$10,000": "Income bracket: Less than $10,000",
      "$10,000_to_$14,999": "Income bracket: $10,000 to $14,999",
      "$15,000_to_$24,999": "Income bracket: $15,000 to $24,999",
      "$25,000_to_$34,999": "Income bracket: $25,000 to $34,999",
      "$35,000_to_$49,999": "Income bracket: $35,000 to $49,999",
      "$50,000_to_$74,999": "Income bracket: $50,000 to $74,999",
      "$75,000_to_$99,999": "Income bracket: $75,000 to $99,999",
      "$100,000_to_$149,999": "Income bracket: $100,000 to $149,999",
      "$150,000_to_$199,999": "Income bracket: $150,000 to $199,999",
      "$200,000_or_more": "Income bracket: $200,000 or more",
      "Median_income": "Median household income (USD)",
      "Mean_income": "Mean household income (USD)",
      "Population_poverty_status_determined": "Population with poverty status determined",
      "Below_poverty_level": "Poverty status: Below poverty level",
      "At_or_above_poverty_level": "Poverty status: At or above poverty level"
    },
    "gov_spending": {
      "state": "State name",
      "Total_Liabilities": "Total debts and obligations",
      "Total_Assets": "Total economic resources owned",
      "Net_Position": "Net wealth (Total Assets - Total Liabilities)",
      "Revenue": "Total revenue from all sources",
      "Expenses": "Total operating expenses",
      "POPULATION": "Population count (for per capita calc)",
      "Current_Assets": "Assets usable within one year (e.g., cash)",
      "Current_Liabilities": "Debts due within one year",
      "Non-Current_Liabilities": "Long-term debts due after one year",
      "Compensated_Absences": "Liability for unused employee leave (vacation/sick)",
      "Net_Pension_Liability": "Unfunded pension obligations",
      "Net_OPEB_Liability": "Unfunded retiree health/benefit obligations (OPEB)",
      "Bonds,_Loans_&_Notes": "Total outstanding principal debt",
      "Free_Cash_Flow": "Cash available after capital expenditures",
      "Current_Ratio": "Liquidity ratio (Current Assets / Current Liabilities)",
      "Debt_Ratio": "Solvency ratio (Total Liabilities / Total Assets)",
      "Total_Liabilities_per_capita": "Total debt burden per capita",
      "Current_Assets_per_capita": "Current assets per capita",
      "Compensated_Absences_per_capita": "Unused employee leave liability per capita",
      "Net_Position_per_capita": "Net financial position per capita",
      "Total_Assets_per_capita": "Total assets per capita",
      "Non-Current_Liabilities_per_capita": "Long-term debt per capita",
      "Bonds,_Loans_&_Notes_per_capita": "Bond and loan debt per capita",
      "Current_Liabilities_per_capita": "Short-term debt per capita",
      "Net_Pension_Liability_per_capita": "Pension debt burden per capita",
      "Free_Cash_Flow_per_capita": "Free cash flow per capita",
      "Expenses_per_capita": "Total spending per capita",
      "Net_OPEB_Liability_per_capita": "Retiree health/benefit debt per capita",
      "Revenue_per_capita": "Total revenue per capita"
    },
    "contract_static": {
      "state": "State name",
      "fed_act_obl": "Federal Contract obligations (direct spending)",
      "fed_act_obl_indirect": "Indirect federal Contract obligations",
      "subaward_amount_out": "Subaward amount paid out (outflow)",
      "subaward_amount_in": "Subaward amount received (inflow)",
      "subaward_amount_net_inflow": "Net subaward inflow (in minus out)",
      "employment": "Employment count",
      "residents": "Resident population count"
    },
    "finra": {
      "state": "State name",
      "financial_constraint": "Financial constraint index (liquidity stress)",
      "fc_norm": "Financial constraint index (normalized)",
      "alternative_financing": "Alternative financing index (use of nontraditional credit)",
      "af_norm": "Alternative financing index (normalized)",
      "financial_literacy": "Financial literacy index (objective knowledge questions)",
      "fl_norm": "Financial literacy index (normalized)",
      "satisfied": "Satisfied with personal financial condition",
      "risk_averse": "Low willingness to take investment risk",
      "too_much_debt": "Reports having too much debt",
      "high_fin_knowledge": "Self-assessed high financial knowledge"
    }
  }
};
